### ISSUE TITLE
https://steamding.tk Is Down - Unable to download .exe

### ISSUE THREAD

**Issue by Jackson0ne** [aquelemiguel/steamding#8]
Hello!

The website hosting the .exe - https://steamding.tk - is down. Not sure if this is temporary or if the project has been discontinued. I would really like to test this out, but if the website no longer exists, would the .exe be able to be hosted as a release here instead please? Or if you could let me know how to compile an .exe from the master myself, I would greatly appreciate it.

Thanks!

**Comment by aquelemiguel** [comment]
Hey, @Jackson0ne!
Thank you for the interest. The project is abandoned right now, I might rewrite it someday. 
The old domain is dead, it's now hosted over at [GitHub Pages](https://aquelemiguel.github.io/steamding/). Thank you for bringing this up!

**Comment by Jackson0ne** [comment]
Hello again,

Thanks for the quick response and for the link! Looking forward to trying this out.

Cheers!
